language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_deploy:
  - ng build --prod
