language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

addons:
  chrome: stable

services:
  - docker

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

after_success:
  - ng build --prod
  - if [ -z "${TRAVIS_TAG}" ]; then
      echo TRAVIS_BRANCH="${TRAVIS_BRANCH}";
      echo TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}";
      docker build -t ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}-SNAPSHOT-${TRAVIS_BUILD_NUMBER} .;
    else
      echo TRAVIS_TAG="${TRAVIS_TAG}";
      docker build -t ${TRAVIS_REPO_SLUG}:${TRAVIS_TAG} -t ${TRAVIS_REPO_SLUG} .;
    fi
